baseurl = "/"
languageCode = "en-us"
title = "Website of the MEE seminar"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/home/"
[[menu.main]]
    name = "Speakers"
    url = "/speakers/"
[[menu.main]]
    name = "Program"
    url = "/program/"
[[menu.main]]
    name = "Registration"
    url = "/registration/"   
[[menu.main]]
    name = "Organizers"
    url = "/organizers/" 
[[menu.main]]
    name = "Editions"
    url = "/editions/" 
[[menu.main]]
    name = "Contact"
    url = "/contact/" 
    
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "Image_MEE.png"
    width = 50
    height = 50
    alt = "Logo"

